<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>bundler</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bundler.Core\Bundler.Core.csproj" />
    <ProjectReference Include="..\Bundler.Nsis\Bundler.Nsis.csproj" />
  </ItemGroup>
</Project>
