<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.5.1" />
    <PackageVersion Include="Interop.UIAutomationClient" Version="10.19041.0" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="17.8.43" />
    <PackageVersion Include="NsisPlugin" Version="1.0.2" />
    <PackageVersion Include="WixToolset.Dtf.WindowsInstaller" Version="5.0.2" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
