<Project>
  <PropertyGroup>
    <BundlerEnabled Condition="'$(BundlerEnabled)' == ''">false</BundlerEnabled>
    <BundlerFormats Condition="'$(BundlerFormats)' == ''">nsis</BundlerFormats>
    <BundlerProductName Condition="'$(BundlerProductName)' == ''"></BundlerProductName>
    <BundlerVersion Condition="'$(BundlerVersion)' == ''"></BundlerVersion>
    <BundlerPublisher Condition="'$(BundlerPublisher)' == ''">$(Company)</BundlerPublisher>
    <BundlerDescription Condition="'$(BundlerDescription)' == ''">$(Description)</BundlerDescription>
    <BundlerHomepage Condition="'$(BundlerHomepage)' == ''">$(PackageProjectUrl)</BundlerHomepage>
    <BundlerCopyright Condition="'$(BundlerCopyright)' == ''">$(Copyright)</BundlerCopyright>
    <BundlerLicenseFile Condition="'$(BundlerLicenseFile)' == ''"></BundlerLicenseFile>
    <BundlerMainExecutable Condition="'$(BundlerMainExecutable)' == ''"></BundlerMainExecutable>
    <BundlerOutputPath Condition="'$(BundlerOutputPath)' == ''">$(MSBuildProjectDirectory)\artifacts</BundlerOutputPath>
    <BundlerToolCachePath Condition="'$(BundlerToolCachePath)' == ''"></BundlerToolCachePath>
    <BundlerWixToolsetArchivePath Condition="'$(BundlerWixToolsetArchivePath)' == ''"></BundlerWixToolsetArchivePath>
    <BundlerWixInstallScope Condition="'$(BundlerWixInstallScope)' == ''">currentUser</BundlerWixInstallScope>
    <BundlerWixUpgradeCode Condition="'$(BundlerWixUpgradeCode)' == ''"></BundlerWixUpgradeCode>
    <BundlerWixVersion Condition="'$(BundlerWixVersion)' == ''"></BundlerWixVersion>
    <BundlerWixAllowDowngrades Condition="'$(BundlerWixAllowDowngrades)' == ''">false</BundlerWixAllowDowngrades>
    <BundlerWixCodepage Condition="'$(BundlerWixCodepage)' == ''">0</BundlerWixCodepage>
    <BundlerWixLanguage Condition="'$(BundlerWixLanguage)' == ''">en-US</BundlerWixLanguage>
    <BundlerWixLanguages Condition="'$(BundlerWixLanguages)' == ''"></BundlerWixLanguages>
    <BundlerWixFipsCompliant Condition="'$(BundlerWixFipsCompliant)' == ''">false</BundlerWixFipsCompliant>
    <BundlerWixStartMenuShortcut Condition="'$(BundlerWixStartMenuShortcut)' == ''">false</BundlerWixStartMenuShortcut>
    <BundlerWixDesktopShortcut Condition="'$(BundlerWixDesktopShortcut)' == ''">false</BundlerWixDesktopShortcut>
    <BundlerWixInstallDirectorySelection Condition="'$(BundlerWixInstallDirectorySelection)' == ''">false</BundlerWixInstallDirectorySelection>
    <BundlerWixBannerFile Condition="'$(BundlerWixBannerFile)' == ''"></BundlerWixBannerFile>
    <BundlerWixDialogFile Condition="'$(BundlerWixDialogFile)' == ''"></BundlerWixDialogFile>
    <BundlerWixAddToPath Condition="'$(BundlerWixAddToPath)' == ''">false</BundlerWixAddToPath>
    <BundlerWixUninstallShortcut Condition="'$(BundlerWixUninstallShortcut)' == ''">false</BundlerWixUninstallShortcut>
    <BundlerWixLaunchAfterInstall Condition="'$(BundlerWixLaunchAfterInstall)' == ''">false</BundlerWixLaunchAfterInstall>
    <BundlerWixExtensionIdPrefix Condition="'$(BundlerWixExtensionIdPrefix)' == ''"></BundlerWixExtensionIdPrefix>
    <BundlerWixExpertTemplateFile Condition="'$(BundlerWixExpertTemplateFile)' == ''"></BundlerWixExpertTemplateFile>
    <BundlerNsisToolsetArchivePath Condition="'$(BundlerNsisToolsetArchivePath)' == ''"></BundlerNsisToolsetArchivePath>
    <BundlerNsisCompilerPath Condition="'$(BundlerNsisCompilerPath)' == ''"></BundlerNsisCompilerPath>
    <BundlerNsisDataDirectory Condition="'$(BundlerNsisDataDirectory)' == ''"></BundlerNsisDataDirectory>
    <BundlerNsisTemplate Condition="'$(BundlerNsisTemplate)' == ''"></BundlerNsisTemplate>
    <BundlerNsisInstallScope Condition="'$(BundlerNsisInstallScope)' == ''">currentUser</BundlerNsisInstallScope>
    <BundlerNsisCompression Condition="'$(BundlerNsisCompression)' == ''">lzma</BundlerNsisCompression>
    <BundlerNsisInstallerIconFile Condition="'$(BundlerNsisInstallerIconFile)' == ''"></BundlerNsisInstallerIconFile>
    <BundlerNsisUninstallerIconFile Condition="'$(BundlerNsisUninstallerIconFile)' == ''"></BundlerNsisUninstallerIconFile>
    <BundlerNsisHeaderFile Condition="'$(BundlerNsisHeaderFile)' == ''"></BundlerNsisHeaderFile>
    <BundlerNsisSidebarFile Condition="'$(BundlerNsisSidebarFile)' == ''"></BundlerNsisSidebarFile>
    <BundlerNsisUninstallerHeaderFile Condition="'$(BundlerNsisUninstallerHeaderFile)' == ''"></BundlerNsisUninstallerHeaderFile>
    <BundlerNsisInstallerHooksFile Condition="'$(BundlerNsisInstallerHooksFile)' == ''"></BundlerNsisInstallerHooksFile>
    <BundlerNsisLanguages Condition="'$(BundlerNsisLanguages)' == ''">English</BundlerNsisLanguages>
    <BundlerNsisDisplayLanguageSelector Condition="'$(BundlerNsisDisplayLanguageSelector)' == ''">false</BundlerNsisDisplayLanguageSelector>
    <BundlerNsisAllowDowngrades Condition="'$(BundlerNsisAllowDowngrades)' == ''">false</BundlerNsisAllowDowngrades>
    <BundlerNsisShortcutDesktop Condition="'$(BundlerNsisShortcutDesktop)' == ''">true</BundlerNsisShortcutDesktop>
    <BundlerNsisShortcutStartMenu Condition="'$(BundlerNsisShortcutStartMenu)' == ''">true</BundlerNsisShortcutStartMenu>
    <BundlerNsisShortcutArguments Condition="'$(BundlerNsisShortcutArguments)' == ''"></BundlerNsisShortcutArguments>
    <BundlerNsisShortcutWorkingDirectory Condition="'$(BundlerNsisShortcutWorkingDirectory)' == ''"></BundlerNsisShortcutWorkingDirectory>
    <BundlerNsisShortcutIcon Condition="'$(BundlerNsisShortcutIcon)' == ''"></BundlerNsisShortcutIcon>
    <BundlerNsisShortcutAppUserModelId Condition="'$(BundlerNsisShortcutAppUserModelId)' == ''"></BundlerNsisShortcutAppUserModelId>
    <BundlerNsisShortcutStartMenuFolder Condition="'$(BundlerNsisShortcutStartMenuFolder)' == ''"></BundlerNsisShortcutStartMenuFolder>
    <BundlerNsisShortcutLegacyProductNames Condition="'$(BundlerNsisShortcutLegacyProductNames)' == ''"></BundlerNsisShortcutLegacyProductNames>
    <BundlerNsisShortcutLegacyMainExecutables Condition="'$(BundlerNsisShortcutLegacyMainExecutables)' == ''"></BundlerNsisShortcutLegacyMainExecutables>
    <BundlerNsisLegacyMsiProductCodes Condition="'$(BundlerNsisLegacyMsiProductCodes)' == ''"></BundlerNsisLegacyMsiProductCodes>
    <BundlerNsisLegacyMsiUpgradeCodes Condition="'$(BundlerNsisLegacyMsiUpgradeCodes)' == ''"></BundlerNsisLegacyMsiUpgradeCodes>
    <BundlerNsisLegacyMsiAutoDetect Condition="'$(BundlerNsisLegacyMsiAutoDetect)' == ''">false</BundlerNsisLegacyMsiAutoDetect>
    <BundlerWindowsSigningPfxFile Condition="'$(BundlerWindowsSigningPfxFile)' == ''"></BundlerWindowsSigningPfxFile>
    <BundlerWindowsSigningPfxPasswordEnvironmentVariable Condition="'$(BundlerWindowsSigningPfxPasswordEnvironmentVariable)' == ''"></BundlerWindowsSigningPfxPasswordEnvironmentVariable>
    <BundlerWindowsSigningCertificateThumbprint Condition="'$(BundlerWindowsSigningCertificateThumbprint)' == ''"></BundlerWindowsSigningCertificateThumbprint>
    <BundlerWindowsSigningCertificateStoreLocation Condition="'$(BundlerWindowsSigningCertificateStoreLocation)' == ''">CurrentUser</BundlerWindowsSigningCertificateStoreLocation>
    <BundlerWindowsSigningTimestampUrl Condition="'$(BundlerWindowsSigningTimestampUrl)' == ''"></BundlerWindowsSigningTimestampUrl>
    <BundlerWindowsSigningCommand Condition="'$(BundlerWindowsSigningCommand)' == ''"></BundlerWindowsSigningCommand>
    <BundlerMacAppPackageName Condition="'$(BundlerMacAppPackageName)' == ''"></BundlerMacAppPackageName>
    <BundlerMacAppDisplayName Condition="'$(BundlerMacAppDisplayName)' == ''"></BundlerMacAppDisplayName>
    <BundlerMacAppShortVersion Condition="'$(BundlerMacAppShortVersion)' == ''"></BundlerMacAppShortVersion>
    <BundlerMacAppBuildVersion Condition="'$(BundlerMacAppBuildVersion)' == ''"></BundlerMacAppBuildVersion>
    <BundlerMacAppMinimumSystemVersion Condition="'$(BundlerMacAppMinimumSystemVersion)' == ''"></BundlerMacAppMinimumSystemVersion>
    <BundlerMacAppCategory Condition="'$(BundlerMacAppCategory)' == ''"></BundlerMacAppCategory>
    <BundlerMacAppIconName Condition="'$(BundlerMacAppIconName)' == ''"></BundlerMacAppIconName>
    <BundlerMacAppSignIdentity Condition="'$(BundlerMacAppSignIdentity)' == ''"></BundlerMacAppSignIdentity>
    <BundlerMacAppTemporaryCertificateFile Condition="'$(BundlerMacAppTemporaryCertificateFile)' == ''"></BundlerMacAppTemporaryCertificateFile>
    <BundlerMacAppTemporaryCertificatePassword Condition="'$(BundlerMacAppTemporaryCertificatePassword)' == ''"></BundlerMacAppTemporaryCertificatePassword>
    <BundlerMacAppHardenedRuntime Condition="'$(BundlerMacAppHardenedRuntime)' == ''">false</BundlerMacAppHardenedRuntime>
    <BundlerMacAppEntitlementsFile Condition="'$(BundlerMacAppEntitlementsFile)' == ''"></BundlerMacAppEntitlementsFile>
    <BundlerMacAppNotarize Condition="'$(BundlerMacAppNotarize)' == ''">false</BundlerMacAppNotarize>
    <BundlerMacAppNotaryWait Condition="'$(BundlerMacAppNotaryWait)' == ''">true</BundlerMacAppNotaryWait>
    <BundlerMacAppSkipStapling Condition="'$(BundlerMacAppSkipStapling)' == ''">false</BundlerMacAppSkipStapling>
    <BundlerMacAppNotaryProfile Condition="'$(BundlerMacAppNotaryProfile)' == ''"></BundlerMacAppNotaryProfile>
    <BundlerMacAppAppleId Condition="'$(BundlerMacAppAppleId)' == ''"></BundlerMacAppAppleId>
    <BundlerMacAppApplePassword Condition="'$(BundlerMacAppApplePassword)' == ''"></BundlerMacAppApplePassword>
    <BundlerMacAppAppleTeamId Condition="'$(BundlerMacAppAppleTeamId)' == ''"></BundlerMacAppAppleTeamId>
    <BundlerMacAppNotaryApiKeyFile Condition="'$(BundlerMacAppNotaryApiKeyFile)' == ''"></BundlerMacAppNotaryApiKeyFile>
    <BundlerMacAppNotaryApiKeyId Condition="'$(BundlerMacAppNotaryApiKeyId)' == ''"></BundlerMacAppNotaryApiKeyId>
    <BundlerMacAppNotaryApiKeyIssuer Condition="'$(BundlerMacAppNotaryApiKeyIssuer)' == ''"></BundlerMacAppNotaryApiKeyIssuer>
    <BundlerMacDmgCompression Condition="'$(BundlerMacDmgCompression)' == ''">Ulmo</BundlerMacDmgCompression>
    <BundlerMacDmgVolumeName Condition="'$(BundlerMacDmgVolumeName)' == ''"></BundlerMacDmgVolumeName>
    <BundlerMacDmgLayoutSkip Condition="'$(BundlerMacDmgLayoutSkip)' == ''">false</BundlerMacDmgLayoutSkip>
    <BundlerMacDmgLayoutWindowX Condition="'$(BundlerMacDmgLayoutWindowX)' == ''">200</BundlerMacDmgLayoutWindowX>
    <BundlerMacDmgLayoutWindowY Condition="'$(BundlerMacDmgLayoutWindowY)' == ''">120</BundlerMacDmgLayoutWindowY>
    <BundlerMacDmgLayoutWindowWidth Condition="'$(BundlerMacDmgLayoutWindowWidth)' == ''">660</BundlerMacDmgLayoutWindowWidth>
    <BundlerMacDmgLayoutWindowHeight Condition="'$(BundlerMacDmgLayoutWindowHeight)' == ''">400</BundlerMacDmgLayoutWindowHeight>
    <BundlerMacDmgLayoutAppIconX Condition="'$(BundlerMacDmgLayoutAppIconX)' == ''">180</BundlerMacDmgLayoutAppIconX>
    <BundlerMacDmgLayoutAppIconY Condition="'$(BundlerMacDmgLayoutAppIconY)' == ''">170</BundlerMacDmgLayoutAppIconY>
    <BundlerMacDmgLayoutApplicationsIconX Condition="'$(BundlerMacDmgLayoutApplicationsIconX)' == ''">480</BundlerMacDmgLayoutApplicationsIconX>
    <BundlerMacDmgLayoutApplicationsIconY Condition="'$(BundlerMacDmgLayoutApplicationsIconY)' == ''">170</BundlerMacDmgLayoutApplicationsIconY>
    <BundlerMacDmgLayoutIconSize Condition="'$(BundlerMacDmgLayoutIconSize)' == ''">128</BundlerMacDmgLayoutIconSize>
    <BundlerMacDmgBackgroundFile Condition="'$(BundlerMacDmgBackgroundFile)' == ''"></BundlerMacDmgBackgroundFile>
    <BundlerMacDmgVolumeIconFile Condition="'$(BundlerMacDmgVolumeIconFile)' == ''"></BundlerMacDmgVolumeIconFile>
    <BundlerMacDmgSignIdentity Condition="'$(BundlerMacDmgSignIdentity)' == ''"></BundlerMacDmgSignIdentity>
    <BundlerMacDmgTemporaryCertificateFile Condition="'$(BundlerMacDmgTemporaryCertificateFile)' == ''"></BundlerMacDmgTemporaryCertificateFile>
    <BundlerMacDmgTemporaryCertificatePassword Condition="'$(BundlerMacDmgTemporaryCertificatePassword)' == ''"></BundlerMacDmgTemporaryCertificatePassword>
    <BundlerMacPkgPackageName Condition="'$(BundlerMacPkgPackageName)' == ''"></BundlerMacPkgPackageName>
    <BundlerMacPkgVersion Condition="'$(BundlerMacPkgVersion)' == ''"></BundlerMacPkgVersion>
    <BundlerMacPkgInstallRoot Condition="'$(BundlerMacPkgInstallRoot)' == ''">/Applications</BundlerMacPkgInstallRoot>
    <BundlerMacPkgTitle Condition="'$(BundlerMacPkgTitle)' == ''"></BundlerMacPkgTitle>
    <BundlerMacPkgWelcomeFile Condition="'$(BundlerMacPkgWelcomeFile)' == ''"></BundlerMacPkgWelcomeFile>
    <BundlerMacPkgConclusionFile Condition="'$(BundlerMacPkgConclusionFile)' == ''"></BundlerMacPkgConclusionFile>
    <BundlerMacPkgInstallScope Condition="'$(BundlerMacPkgInstallScope)' == ''">System</BundlerMacPkgInstallScope>
    <BundlerMacPkgScriptsDirectory Condition="'$(BundlerMacPkgScriptsDirectory)' == ''"></BundlerMacPkgScriptsDirectory>
    <BundlerMacPkgSignIdentity Condition="'$(BundlerMacPkgSignIdentity)' == ''"></BundlerMacPkgSignIdentity>
    <BundlerMacPkgTemporaryCertificateFile Condition="'$(BundlerMacPkgTemporaryCertificateFile)' == ''"></BundlerMacPkgTemporaryCertificateFile>
    <BundlerMacPkgTemporaryCertificatePassword Condition="'$(BundlerMacPkgTemporaryCertificatePassword)' == ''"></BundlerMacPkgTemporaryCertificatePassword>
    <BundlerMacPkgNotarize Condition="'$(BundlerMacPkgNotarize)' == ''">false</BundlerMacPkgNotarize>
    <BundlerMacPkgNotaryWait Condition="'$(BundlerMacPkgNotaryWait)' == ''">true</BundlerMacPkgNotaryWait>
    <BundlerMacPkgSkipStapling Condition="'$(BundlerMacPkgSkipStapling)' == ''">false</BundlerMacPkgSkipStapling>
    <BundlerMacPkgNotaryProfile Condition="'$(BundlerMacPkgNotaryProfile)' == ''"></BundlerMacPkgNotaryProfile>
    <BundlerMacPkgAppleId Condition="'$(BundlerMacPkgAppleId)' == ''"></BundlerMacPkgAppleId>
    <BundlerMacPkgApplePassword Condition="'$(BundlerMacPkgApplePassword)' == ''"></BundlerMacPkgApplePassword>
    <BundlerMacPkgAppleTeamId Condition="'$(BundlerMacPkgAppleTeamId)' == ''"></BundlerMacPkgAppleTeamId>
    <BundlerMacPkgNotaryApiKeyFile Condition="'$(BundlerMacPkgNotaryApiKeyFile)' == ''"></BundlerMacPkgNotaryApiKeyFile>
    <BundlerMacPkgNotaryApiKeyId Condition="'$(BundlerMacPkgNotaryApiKeyId)' == ''"></BundlerMacPkgNotaryApiKeyId>
    <BundlerMacPkgNotaryApiKeyIssuer Condition="'$(BundlerMacPkgNotaryApiKeyIssuer)' == ''"></BundlerMacPkgNotaryApiKeyIssuer>
    <BundlerDebPackageName Condition="'$(BundlerDebPackageName)' == ''"></BundlerDebPackageName>
    <BundlerDebVersion Condition="'$(BundlerDebVersion)' == ''"></BundlerDebVersion>
    <BundlerDebRelease Condition="'$(BundlerDebRelease)' == ''"></BundlerDebRelease>
    <BundlerDebEpoch Condition="'$(BundlerDebEpoch)' == ''"></BundlerDebEpoch>
    <BundlerDebArchitecture Condition="'$(BundlerDebArchitecture)' == ''"></BundlerDebArchitecture>
    <BundlerDebVendor Condition="'$(BundlerDebVendor)' == ''"></BundlerDebVendor>
    <BundlerDebInstallRoot Condition="'$(BundlerDebInstallRoot)' == ''"></BundlerDebInstallRoot>
    <BundlerDebBinLink Condition="'$(BundlerDebBinLink)' == ''"></BundlerDebBinLink>
    <BundlerDebDepends Condition="'$(BundlerDebDepends)' == ''"></BundlerDebDepends>
    <BundlerDebRecommends Condition="'$(BundlerDebRecommends)' == ''"></BundlerDebRecommends>
    <BundlerDebProvides Condition="'$(BundlerDebProvides)' == ''"></BundlerDebProvides>
    <BundlerDebConflicts Condition="'$(BundlerDebConflicts)' == ''"></BundlerDebConflicts>
    <BundlerDebReplaces Condition="'$(BundlerDebReplaces)' == ''"></BundlerDebReplaces>
    <BundlerDebSection Condition="'$(BundlerDebSection)' == ''"></BundlerDebSection>
    <BundlerDebPriority Condition="'$(BundlerDebPriority)' == ''"></BundlerDebPriority>
    <BundlerDebCategories Condition="'$(BundlerDebCategories)' == ''"></BundlerDebCategories>
    <BundlerDebDesktopFile Condition="'$(BundlerDebDesktopFile)' == ''"></BundlerDebDesktopFile>
    <BundlerDebMetainfoFile Condition="'$(BundlerDebMetainfoFile)' == ''"></BundlerDebMetainfoFile>
    <BundlerDebChangelogFile Condition="'$(BundlerDebChangelogFile)' == ''"></BundlerDebChangelogFile>
    <BundlerDebPreInstallFile Condition="'$(BundlerDebPreInstallFile)' == ''"></BundlerDebPreInstallFile>
    <BundlerDebPostInstallFile Condition="'$(BundlerDebPostInstallFile)' == ''"></BundlerDebPostInstallFile>
    <BundlerDebPreUninstallFile Condition="'$(BundlerDebPreUninstallFile)' == ''"></BundlerDebPreUninstallFile>
    <BundlerDebPostUninstallFile Condition="'$(BundlerDebPostUninstallFile)' == ''"></BundlerDebPostUninstallFile>
    <BundlerDebSystemdServiceFile Condition="'$(BundlerDebSystemdServiceFile)' == ''"></BundlerDebSystemdServiceFile>
    <BundlerDebConfigLocations Condition="'$(BundlerDebConfigLocations)' == ''"></BundlerDebConfigLocations>
    <BundlerRpmPackageName Condition="'$(BundlerRpmPackageName)' == ''"></BundlerRpmPackageName>
    <BundlerRpmVersion Condition="'$(BundlerRpmVersion)' == ''"></BundlerRpmVersion>
    <BundlerRpmRelease Condition="'$(BundlerRpmRelease)' == ''"></BundlerRpmRelease>
    <BundlerRpmEpoch Condition="'$(BundlerRpmEpoch)' == ''"></BundlerRpmEpoch>
    <BundlerRpmArchitecture Condition="'$(BundlerRpmArchitecture)' == ''"></BundlerRpmArchitecture>
    <BundlerRpmVendor Condition="'$(BundlerRpmVendor)' == ''"></BundlerRpmVendor>
    <BundlerRpmInstallRoot Condition="'$(BundlerRpmInstallRoot)' == ''"></BundlerRpmInstallRoot>
    <BundlerRpmBinLink Condition="'$(BundlerRpmBinLink)' == ''"></BundlerRpmBinLink>
    <BundlerRpmDepends Condition="'$(BundlerRpmDepends)' == ''"></BundlerRpmDepends>
    <BundlerRpmProvides Condition="'$(BundlerRpmProvides)' == ''"></BundlerRpmProvides>
    <BundlerRpmConflicts Condition="'$(BundlerRpmConflicts)' == ''"></BundlerRpmConflicts>
    <BundlerRpmObsoletes Condition="'$(BundlerRpmObsoletes)' == ''"></BundlerRpmObsoletes>
    <BundlerRpmRecommends Condition="'$(BundlerRpmRecommends)' == ''"></BundlerRpmRecommends>
    <BundlerRpmSuggests Condition="'$(BundlerRpmSuggests)' == ''"></BundlerRpmSuggests>
    <BundlerRpmLicense Condition="'$(BundlerRpmLicense)' == ''"></BundlerRpmLicense>
    <BundlerRpmGroup Condition="'$(BundlerRpmGroup)' == ''"></BundlerRpmGroup>
    <BundlerRpmUrl Condition="'$(BundlerRpmUrl)' == ''"></BundlerRpmUrl>
    <BundlerRpmCategories Condition="'$(BundlerRpmCategories)' == ''"></BundlerRpmCategories>
    <BundlerRpmDesktopFile Condition="'$(BundlerRpmDesktopFile)' == ''"></BundlerRpmDesktopFile>
    <BundlerRpmMetainfoFile Condition="'$(BundlerRpmMetainfoFile)' == ''"></BundlerRpmMetainfoFile>
    <BundlerRpmChangelogFile Condition="'$(BundlerRpmChangelogFile)' == ''"></BundlerRpmChangelogFile>
    <BundlerRpmConfigLocations Condition="'$(BundlerRpmConfigLocations)' == ''"></BundlerRpmConfigLocations>
    <BundlerRpmSystemdServiceFile Condition="'$(BundlerRpmSystemdServiceFile)' == ''"></BundlerRpmSystemdServiceFile>
    <BundlerRpmPreInstallFile Condition="'$(BundlerRpmPreInstallFile)' == ''"></BundlerRpmPreInstallFile>
    <BundlerRpmPostInstallFile Condition="'$(BundlerRpmPostInstallFile)' == ''"></BundlerRpmPostInstallFile>
    <BundlerRpmPreUninstallFile Condition="'$(BundlerRpmPreUninstallFile)' == ''"></BundlerRpmPreUninstallFile>
    <BundlerRpmPostUninstallFile Condition="'$(BundlerRpmPostUninstallFile)' == ''"></BundlerRpmPostUninstallFile>
    <BundlerRpmPreInstallProgram Condition="'$(BundlerRpmPreInstallProgram)' == ''"></BundlerRpmPreInstallProgram>
    <BundlerRpmPostInstallProgram Condition="'$(BundlerRpmPostInstallProgram)' == ''"></BundlerRpmPostInstallProgram>
    <BundlerRpmPreUninstallProgram Condition="'$(BundlerRpmPreUninstallProgram)' == ''"></BundlerRpmPreUninstallProgram>
    <BundlerRpmPostUninstallProgram Condition="'$(BundlerRpmPostUninstallProgram)' == ''"></BundlerRpmPostUninstallProgram>
    <BundlerAppImagePackageName Condition="'$(BundlerAppImagePackageName)' == ''"></BundlerAppImagePackageName>
    <BundlerAppImageVersion Condition="'$(BundlerAppImageVersion)' == ''"></BundlerAppImageVersion>
    <BundlerAppImageArchitecture Condition="'$(BundlerAppImageArchitecture)' == ''"></BundlerAppImageArchitecture>
    <BundlerAppImageInstallRoot Condition="'$(BundlerAppImageInstallRoot)' == ''"></BundlerAppImageInstallRoot>
    <BundlerAppImageBinLink Condition="'$(BundlerAppImageBinLink)' == ''"></BundlerAppImageBinLink>
    <BundlerAppImageIconFile Condition="'$(BundlerAppImageIconFile)' == ''"></BundlerAppImageIconFile>
    <BundlerAppImageDesktopFile Condition="'$(BundlerAppImageDesktopFile)' == ''"></BundlerAppImageDesktopFile>
    <BundlerAppImageCategories Condition="'$(BundlerAppImageCategories)' == ''"></BundlerAppImageCategories>
    <BundlerAppImageMetainfoFile Condition="'$(BundlerAppImageMetainfoFile)' == ''"></BundlerAppImageMetainfoFile>
    <BundlerArchivePackageName Condition="'$(BundlerArchivePackageName)' == ''"></BundlerArchivePackageName>
    <BundlerArchiveVersion Condition="'$(BundlerArchiveVersion)' == ''"></BundlerArchiveVersion>
    <BundlerArchiveName Condition="'$(BundlerArchiveName)' == ''"></BundlerArchiveName>
    <BundlerAlpineApkPackageName Condition="'$(BundlerAlpineApkPackageName)' == ''"></BundlerAlpineApkPackageName>
    <BundlerAlpineApkVersion Condition="'$(BundlerAlpineApkVersion)' == ''"></BundlerAlpineApkVersion>
    <BundlerAlpineApkArchitecture Condition="'$(BundlerAlpineApkArchitecture)' == ''"></BundlerAlpineApkArchitecture>
    <BundlerAlpineApkOrigin Condition="'$(BundlerAlpineApkOrigin)' == ''"></BundlerAlpineApkOrigin>
    <BundlerAlpineApkDescription Condition="'$(BundlerAlpineApkDescription)' == ''"></BundlerAlpineApkDescription>
    <BundlerAlpineApkUrl Condition="'$(BundlerAlpineApkUrl)' == ''"></BundlerAlpineApkUrl>
    <BundlerAlpineApkBinLink Condition="'$(BundlerAlpineApkBinLink)' == ''"></BundlerAlpineApkBinLink>
    <BundlerAlpineApkRelease Condition="'$(BundlerAlpineApkRelease)' == ''"></BundlerAlpineApkRelease>
    <BundlerAlpineApkLicense Condition="'$(BundlerAlpineApkLicense)' == ''"></BundlerAlpineApkLicense>
    <BundlerAlpineApkBuildDate Condition="'$(BundlerAlpineApkBuildDate)' == ''"></BundlerAlpineApkBuildDate>
    <BundlerAlpineApkDepends Condition="'$(BundlerAlpineApkDepends)' == ''"></BundlerAlpineApkDepends>
    <BundlerAlpineApkProvides Condition="'$(BundlerAlpineApkProvides)' == ''"></BundlerAlpineApkProvides>
    <BundlerAlpineApkTriggers Condition="'$(BundlerAlpineApkTriggers)' == ''"></BundlerAlpineApkTriggers>
    <BundlerAlpineApkPreInstallFile Condition="'$(BundlerAlpineApkPreInstallFile)' == ''"></BundlerAlpineApkPreInstallFile>
    <BundlerAlpineApkPostInstallFile Condition="'$(BundlerAlpineApkPostInstallFile)' == ''"></BundlerAlpineApkPostInstallFile>
    <BundlerAlpineApkPreUninstallFile Condition="'$(BundlerAlpineApkPreUninstallFile)' == ''"></BundlerAlpineApkPreUninstallFile>
    <BundlerAlpineApkPostUninstallFile Condition="'$(BundlerAlpineApkPostUninstallFile)' == ''"></BundlerAlpineApkPostUninstallFile>
    <BundlerAlpineApkPreUpgradeFile Condition="'$(BundlerAlpineApkPreUpgradeFile)' == ''"></BundlerAlpineApkPreUpgradeFile>
    <BundlerAlpineApkPostUpgradeFile Condition="'$(BundlerAlpineApkPostUpgradeFile)' == ''"></BundlerAlpineApkPostUpgradeFile>
    <BundlerAlpineApkSigningKeyFile Condition="'$(BundlerAlpineApkSigningKeyFile)' == ''"></BundlerAlpineApkSigningKeyFile>
    <BundlerAlpineApkSigningKeyPassphrase Condition="'$(BundlerAlpineApkSigningKeyPassphrase)' == ''"></BundlerAlpineApkSigningKeyPassphrase>
  </PropertyGroup>
</Project>
