<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>DotNet.Bundler</PackageId>
    <Description>Convenience package for automatic desktop installer generation during dotnet publish.</Description>
    <PackageTags>dotnet;msbuild;bundler;installer;desktop</PackageTags>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecFile>DotNet.Bundler.nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
    <NuspecProperties>version=$(BundlerPackageVersion)</NuspecProperties>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bundler.MSBuild\Bundler.MSBuild.csproj" PrivateAssets="all" />
  </ItemGroup>
</Project>
