<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Bundler.Core\Bundler.Core.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Nsis\Bundler.Nsis.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Wix\Bundler.Wix.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Signing.Windows\Bundler.Signing.Windows.csproj" />
  </ItemGroup>
</Project>
