<Project>
  <PropertyGroup>
    <BundlerEnabled Condition="'$(BundlerEnabled)' == ''">false</BundlerEnabled>
    <BundlerFormats Condition="'$(BundlerFormats)' == ''">nsis</BundlerFormats>
    <BundlerProductName Condition="'$(BundlerProductName)' == ''"></BundlerProductName>
    <BundlerVersion Condition="'$(BundlerVersion)' == ''"></BundlerVersion>
    <BundlerPublisher Condition="'$(BundlerPublisher)' == ''">$(Company)</BundlerPublisher>
    <BundlerDescription Condition="'$(BundlerDescription)' == ''">$(Description)</BundlerDescription>
    <BundlerHomepage Condition="'$(BundlerHomepage)' == ''">$(PackageProjectUrl)</BundlerHomepage>
    <BundlerCopyright Condition="'$(BundlerCopyright)' == ''">$(Copyright)</BundlerCopyright>
    <BundlerLicenseFile Condition="'$(BundlerLicenseFile)' == ''"></BundlerLicenseFile>
    <BundlerMainExecutable Condition="'$(BundlerMainExecutable)' == ''"></BundlerMainExecutable>
    <BundlerOutputPath Condition="'$(BundlerOutputPath)' == ''">$(MSBuildProjectDirectory)\artifacts</BundlerOutputPath>
    <BundlerToolCachePath Condition="'$(BundlerToolCachePath)' == ''"></BundlerToolCachePath>
    <BundlerWixToolsetArchivePath Condition="'$(BundlerWixToolsetArchivePath)' == ''"></BundlerWixToolsetArchivePath>
    <BundlerWixInstallScope Condition="'$(BundlerWixInstallScope)' == ''">currentUser</BundlerWixInstallScope>
    <BundlerWixUpgradeCode Condition="'$(BundlerWixUpgradeCode)' == ''"></BundlerWixUpgradeCode>
    <BundlerWixMsiVersion Condition="'$(BundlerWixMsiVersion)' == ''"></BundlerWixMsiVersion>
    <BundlerWixAllowDowngrades Condition="'$(BundlerWixAllowDowngrades)' == ''">false</BundlerWixAllowDowngrades>
    <BundlerWixCodepage Condition="'$(BundlerWixCodepage)' == ''">0</BundlerWixCodepage>
    <BundlerWixLanguage Condition="'$(BundlerWixLanguage)' == ''">en-US</BundlerWixLanguage>
    <BundlerWixLanguages Condition="'$(BundlerWixLanguages)' == ''"></BundlerWixLanguages>
    <BundlerWixFipsCompliant Condition="'$(BundlerWixFipsCompliant)' == ''">false</BundlerWixFipsCompliant>
    <BundlerWixStartMenuShortcut Condition="'$(BundlerWixStartMenuShortcut)' == ''">false</BundlerWixStartMenuShortcut>
    <BundlerWixDesktopShortcut Condition="'$(BundlerWixDesktopShortcut)' == ''">false</BundlerWixDesktopShortcut>
    <BundlerWixInstallDirectorySelection Condition="'$(BundlerWixInstallDirectorySelection)' == ''">false</BundlerWixInstallDirectorySelection>
    <BundlerWixBannerBitmap Condition="'$(BundlerWixBannerBitmap)' == ''"></BundlerWixBannerBitmap>
    <BundlerWixDialogBitmap Condition="'$(BundlerWixDialogBitmap)' == ''"></BundlerWixDialogBitmap>
    <BundlerWixAddToPath Condition="'$(BundlerWixAddToPath)' == ''">false</BundlerWixAddToPath>
    <BundlerWixUninstallShortcut Condition="'$(BundlerWixUninstallShortcut)' == ''">false</BundlerWixUninstallShortcut>
    <BundlerWixLaunchAfterInstall Condition="'$(BundlerWixLaunchAfterInstall)' == ''">false</BundlerWixLaunchAfterInstall>
    <BundlerWixExtensionIdPrefix Condition="'$(BundlerWixExtensionIdPrefix)' == ''"></BundlerWixExtensionIdPrefix>
    <BundlerWixExpertTemplate Condition="'$(BundlerWixExpertTemplate)' == ''"></BundlerWixExpertTemplate>
    <BundlerNsisToolsetArchivePath Condition="'$(BundlerNsisToolsetArchivePath)' == ''"></BundlerNsisToolsetArchivePath>
    <BundlerNsisCompilerPath Condition="'$(BundlerNsisCompilerPath)' == ''"></BundlerNsisCompilerPath>
    <BundlerNsisDataDirectory Condition="'$(BundlerNsisDataDirectory)' == ''"></BundlerNsisDataDirectory>
    <BundlerNsisTemplate Condition="'$(BundlerNsisTemplate)' == ''"></BundlerNsisTemplate>
    <BundlerNsisInstallMode Condition="'$(BundlerNsisInstallMode)' == ''">currentUser</BundlerNsisInstallMode>
    <BundlerNsisCompression Condition="'$(BundlerNsisCompression)' == ''">lzma</BundlerNsisCompression>
    <BundlerNsisInstallerIcon Condition="'$(BundlerNsisInstallerIcon)' == ''"></BundlerNsisInstallerIcon>
    <BundlerNsisUninstallerIcon Condition="'$(BundlerNsisUninstallerIcon)' == ''"></BundlerNsisUninstallerIcon>
    <BundlerNsisHeaderImage Condition="'$(BundlerNsisHeaderImage)' == ''"></BundlerNsisHeaderImage>
    <BundlerNsisSidebarImage Condition="'$(BundlerNsisSidebarImage)' == ''"></BundlerNsisSidebarImage>
    <BundlerNsisUninstallerHeaderImage Condition="'$(BundlerNsisUninstallerHeaderImage)' == ''"></BundlerNsisUninstallerHeaderImage>
    <BundlerNsisInstallerHooks Condition="'$(BundlerNsisInstallerHooks)' == ''"></BundlerNsisInstallerHooks>
    <BundlerNsisLanguages Condition="'$(BundlerNsisLanguages)' == ''">English</BundlerNsisLanguages>
    <BundlerNsisDisplayLanguageSelector Condition="'$(BundlerNsisDisplayLanguageSelector)' == ''">false</BundlerNsisDisplayLanguageSelector>
    <BundlerNsisAllowDowngrades Condition="'$(BundlerNsisAllowDowngrades)' == ''">false</BundlerNsisAllowDowngrades>
    <BundlerNsisShortcutDesktop Condition="'$(BundlerNsisShortcutDesktop)' == ''">true</BundlerNsisShortcutDesktop>
    <BundlerNsisShortcutStartMenu Condition="'$(BundlerNsisShortcutStartMenu)' == ''">true</BundlerNsisShortcutStartMenu>
    <BundlerNsisShortcutArguments Condition="'$(BundlerNsisShortcutArguments)' == ''"></BundlerNsisShortcutArguments>
    <BundlerNsisShortcutWorkingDirectory Condition="'$(BundlerNsisShortcutWorkingDirectory)' == ''"></BundlerNsisShortcutWorkingDirectory>
    <BundlerNsisShortcutIcon Condition="'$(BundlerNsisShortcutIcon)' == ''"></BundlerNsisShortcutIcon>
    <BundlerNsisShortcutAppUserModelId Condition="'$(BundlerNsisShortcutAppUserModelId)' == ''"></BundlerNsisShortcutAppUserModelId>
    <BundlerNsisShortcutStartMenuFolder Condition="'$(BundlerNsisShortcutStartMenuFolder)' == ''"></BundlerNsisShortcutStartMenuFolder>
    <BundlerNsisShortcutLegacyProductNames Condition="'$(BundlerNsisShortcutLegacyProductNames)' == ''"></BundlerNsisShortcutLegacyProductNames>
    <BundlerNsisShortcutLegacyMainExecutables Condition="'$(BundlerNsisShortcutLegacyMainExecutables)' == ''"></BundlerNsisShortcutLegacyMainExecutables>
    <BundlerNsisLegacyMsiProductCodes Condition="'$(BundlerNsisLegacyMsiProductCodes)' == ''"></BundlerNsisLegacyMsiProductCodes>
    <BundlerNsisLegacyMsiUpgradeCodes Condition="'$(BundlerNsisLegacyMsiUpgradeCodes)' == ''"></BundlerNsisLegacyMsiUpgradeCodes>
    <BundlerNsisLegacyMsiAutoDetect Condition="'$(BundlerNsisLegacyMsiAutoDetect)' == ''">false</BundlerNsisLegacyMsiAutoDetect>
    <BundlerWindowsSigningPfxFile Condition="'$(BundlerWindowsSigningPfxFile)' == ''"></BundlerWindowsSigningPfxFile>
    <BundlerWindowsSigningPfxPasswordEnvironmentVariable Condition="'$(BundlerWindowsSigningPfxPasswordEnvironmentVariable)' == ''"></BundlerWindowsSigningPfxPasswordEnvironmentVariable>
    <BundlerWindowsSigningCertificateThumbprint Condition="'$(BundlerWindowsSigningCertificateThumbprint)' == ''"></BundlerWindowsSigningCertificateThumbprint>
    <BundlerWindowsSigningCertificateStoreLocation Condition="'$(BundlerWindowsSigningCertificateStoreLocation)' == ''">CurrentUser</BundlerWindowsSigningCertificateStoreLocation>
    <BundlerWindowsSigningTimestampUrl Condition="'$(BundlerWindowsSigningTimestampUrl)' == ''"></BundlerWindowsSigningTimestampUrl>
    <BundlerWindowsSigningCommand Condition="'$(BundlerWindowsSigningCommand)' == ''"></BundlerWindowsSigningCommand>
  </PropertyGroup>
</Project>
