<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <RestoreSources>$(MSBuildThisFileDirectory)..\..\artifacts\packages</RestoreSources>

    <BundlerEnabled>true</BundlerEnabled>
    <BundlerIdentifier>com.example.hellobundledapp</BundlerIdentifier>
    <BundlerProductName>Hello Bundled App</BundlerProductName>
    <BundlerPublisher>Bundler Contributors</BundlerPublisher>
    <BundlerNsisLanguages>English;SimpChinese</BundlerNsisLanguages>
    <BundlerNsisDisplayLanguageSelector>true</BundlerNsisDisplayLanguageSelector>



    <Version>1.0.0</Version>
    <BundlerNsisAllowDowngrades>true</BundlerNsisAllowDowngrades>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.Bundler" Version="0.1.0-alpha.15" PrivateAssets="all" />
  </ItemGroup>
</Project>
