using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using DotNet.Bundler;
using DotNet.Bundler.Core;

namespace DotNet.Bundler.Deb;

/// <summary>
/// Emits a .deb entirely in managed code:
/// an ar archive holding debian-binary, control.tar.gz and data.tar.gz.
/// No host packaging tools are invoked, so the writer runs on any .NET host.
/// </summary>
internal static class DebPackageWriter
{
    internal sealed class Result
    {
        internal string OutputPath = "";
        internal string PackageName = "";
        internal string Version = "";
        internal string Architecture = "";
    }

    private sealed class PayloadEntry
    {
        internal string ArchivePath = "";   // e.g. "usr/lib/pkg/app" (no leading './')
        internal TarEntryKind Kind;
        internal int Mode;
        internal string? SourcePath;        // host file for Kind=File
        internal byte[]? Content;           // generated bytes for Kind=File without SourcePath
        internal string LinkTarget = "";    // for Kind=Symlink
        internal long Size;                 // file size for Installed-Size/md5sums
    }

    internal static Result Build(
        BundleConfiguration bundle,
        BundlePlanItem item,
        DebBundleConfiguration settings,
        IBundleLogger logger)
    {
        var packageName = settings.PackageName ?? DebName.Sanitize(bundle.ProductName);
        DebName.Validate(packageName);
        var version = DebVersion.Map(bundle.Version, settings);
        var architecture = settings.Architecture ?? MapArchitecture(item.Target.Architecture);
        ValidateArchitecture(architecture);
        var installRoot = NormalizeInstallRoot(settings.InstallRoot, packageName);
        var binLink = settings.BinLink ?? packageName;
        // 与 rpm/appimage/apk 同规："none" 是关闭语义，不产字面 usr/bin/none 链接。
        if (string.Equals(binLink, "none", StringComparison.OrdinalIgnoreCase))
        {
            binLink = "";
        }
        if (binLink.Length > 0)
        {
            ValidateBinLinkName(binLink);
        }
        var maintainer = settings.Vendor ?? bundle.Publisher ?? bundle.Identifier;
        if (string.IsNullOrWhiteSpace(maintainer) || maintainer.IndexOfAny(['\r', '\n']) >= 0)
        {
            throw new ArgumentException(
                "The .deb maintainer must be a non-empty single line; set Publisher or Vendor.");
        }

        var payload = CollectPayload(bundle, item, installRoot, binLink, packageName, version, maintainer, settings, logger);
        // data.tar.gz 是大件：tar 直写 gzip→输出目录旁的临时文件（/tmp 小卷不堵
        // 构建——目标目录反正得装下成品），ar 装配时流式拷贝——全程不驻内存。
        // control.tar.gz 只有维护脚本与元数据（KB 级），留内存路径。
        Directory.CreateDirectory(item.OutputDirectory);
        var dataTarGzPath = Path.Combine(item.OutputDirectory,
            ".bundler-deb-" + Guid.NewGuid().ToString("N") + ".tar.gz");
        try
        {
            GzipTarToFile(payload, dataTarGzPath);
            var controlTarGz = Gzip(TarBytes(ControlEntries(bundle, payload, packageName, version,
                architecture, maintainer, settings)));

            var fileName = packageName + "_" + DebVersion.FileNameVersion(version) + "_" +
                architecture + ".deb";
            var outputPath = Path.Combine(item.OutputDirectory, fileName);
            var sidecarPath = outputPath + ".sha256";
            try
            {
                Directory.CreateDirectory(item.OutputDirectory);
                using (var stream = File.Create(outputPath))
                {
                    ArWriter.Write(stream,
                    [
                        new ArMember("debian-binary", Encoding.ASCII.GetBytes("2.0\n")),
                        new ArMember("control.tar.gz", controlTarGz),
                        ArMember.FromFile("data.tar.gz", dataTarGzPath)
                    ]);
                }
                var hash = Sha256HexFile(outputPath);
                File.WriteAllText(sidecarPath,
                    hash + "  " + fileName + "\n", new UTF8Encoding(false));
                logger.Log(BundleLogLevel.Information, $"Wrote {fileName} (sha256 {hash}).");
                return new Result
                {
                    OutputPath = outputPath,
                    PackageName = packageName,
                    Version = version,
                    Architecture = architecture
                };
            }
            catch
            {
                if (File.Exists(outputPath))
                {
                    File.Delete(outputPath);
                }
                if (File.Exists(sidecarPath))
                {
                    File.Delete(sidecarPath);
                }
                throw;
            }
        }
        finally
        {
            TryDelete(dataTarGzPath);
        }
    }

    private static List<PayloadEntry> CollectPayload(
        BundleConfiguration bundle,
        BundlePlanItem item,
        string installRoot,
        string binLink,
        string packageName,
        string version,
        string maintainer,
        DebBundleConfiguration settings,
        IBundleLogger logger)
    {
        var entries = new List<PayloadEntry>();
        var claimed = new HashSet<string>(StringComparer.Ordinal);
        var directories = new HashSet<string>(StringComparer.Ordinal);

        void ClaimDirectory(string path)
        {
            var segments = path.Split('/');
            for (var i = 1; i <= segments.Length; i++)
            {
                var prefix = string.Join("/", segments.Take(i));
                if (claimed.Contains(prefix))
                {
                    throw new InvalidOperationException(
                        $"A payload file and a directory map to the same .deb path: '{prefix}'.");
                }
                if (directories.Add(prefix))
                {
                    entries.Add(new PayloadEntry
                    {
                        ArchivePath = prefix,
                        Kind = TarEntryKind.Directory,
                        Mode = 493 /* 0755 */
                    });
                }
            }
        }

        void AddFile(string archivePath, string sourcePath, int mode)
        {
            ClaimDirectory(archivePath.Substring(0, archivePath.LastIndexOf('/')));
            // claimed 只收文件/链接；撞上已落目录的同路径文件同样要显式拒绝。
            if (directories.Contains(archivePath) || !claimed.Add(archivePath))
            {
                throw new InvalidOperationException(
                    $"Two payload sources map to the same .deb path: '{archivePath}'.");
            }
            var info = new FileInfo(sourcePath);
            entries.Add(new PayloadEntry
            {
                ArchivePath = archivePath,
                Kind = TarEntryKind.File,
                Mode = mode,
                SourcePath = sourcePath,
                Size = info.Length
            });
        }

        void AddGeneratedFile(string archivePath, byte[] content, int mode)
        {
            ClaimDirectory(archivePath.Substring(0, archivePath.LastIndexOf('/')));
            if (directories.Contains(archivePath) || !claimed.Add(archivePath))
            {
                throw new InvalidOperationException(
                    $"Two payload sources map to the same .deb path: '{archivePath}'.");
            }
            entries.Add(new PayloadEntry
            {
                ArchivePath = archivePath,
                Kind = TarEntryKind.File,
                Mode = mode,
                Content = content,
                Size = content.Length
            });
        }

        var input = item.InputDirectory;
        var mainExecutable = item.MainExecutable.Replace('\\', '/');
        foreach (var directory in Directory.GetDirectories(input, "*", SearchOption.AllDirectories)
                     .OrderBy(path => path, StringComparer.Ordinal))
        {
            var relative = ToPosixPath(RelativePath(input, directory));
            var archivePath = installRoot + "/" + relative;
            ClaimDirectory(archivePath.Substring(0, archivePath.LastIndexOf('/')));
            if (directories.Add(archivePath))
            {
                entries.Add(new PayloadEntry
                {
                    ArchivePath = archivePath,
                    Kind = TarEntryKind.Directory,
                    Mode = 493 /* 0755 */
                });
            }
        }
        foreach (var file in Directory.GetFiles(input, "*", SearchOption.AllDirectories)
                     .OrderBy(path => path, StringComparer.Ordinal))
        {
            // Sockets, FIFOs and device nodes cannot be packaged; skip them.
            if (!UnixFileTypes.IsRegularFile(file))
            {
                logger.Log(BundleLogLevel.Warning, $"Skipping non-regular file: {file}");
                continue;
            }
            var relative = ToPosixPath(RelativePath(input, file));
            var mode = string.Equals(relative, mainExecutable, StringComparison.Ordinal)
                ? 493 /* 0755 */
                : 420 /* 0644 */;
            AddFile(installRoot + "/" + relative, file, mode);
        }

        foreach (var resource in bundle.Resources)
        {
            var target = resource.Destination.Replace('\\', '/').Trim('/');
            if (target.Length == 0 || target.Split('/').Contains(".."))
            {
                throw new ArgumentException(
                    $"The resource target must stay inside the payload: '{resource.Destination}'.");
            }
            var source = Path.GetFullPath(resource.Source);
            if (Directory.Exists(source))
            {
                foreach (var file in Directory.GetFiles(source, "*", SearchOption.AllDirectories)
                             .OrderBy(path => path, StringComparer.Ordinal))
                {
                    if (!UnixFileTypes.IsRegularFile(file))
                    {
                        logger.Log(BundleLogLevel.Warning, $"Skipping non-regular file: {file}");
                        continue;
                    }
                    var relative = ToPosixPath(RelativePath(source, file));
                    AddFile(installRoot + "/" + target + "/" + relative, file, 420 /* 0644 */);
                }
            }
            else if (File.Exists(source))
            {
                AddFile(installRoot + "/" + target, source, 420 /* 0644 */);
            }
            else
            {
                throw new FileNotFoundException(
                    $"The resource source does not exist: {source}", source);
            }
        }

        if (binLink.Length > 0)
        {
            var linkPath = "usr/bin/" + binLink;
            if (!claimed.Add(linkPath))
            {
                throw new InvalidOperationException(
                    $"A payload file already occupies the bin-link path: '{linkPath}'.");
            }
            ClaimDirectory("usr/bin");
            // Links under /usr/bin use a relative target for usr/* roots and an
            // absolute target for other roots (e.g. /opt/<name>).
            var target = installRoot.StartsWith("usr/", StringComparison.Ordinal)
                ? "../" + installRoot.Substring(4) + "/" + mainExecutable
                : "/" + installRoot + "/" + mainExecutable;
            entries.Add(new PayloadEntry
            {
                ArchivePath = linkPath,
                Kind = TarEntryKind.Symlink,
                Mode = 511 /* 0777 */,
                LinkTarget = target
            });
        }

        // Desktop integration (shared with the .rpm backend): a generated or
        // caller-supplied .desktop entry, hicolor icons and optional metainfo.
        foreach (var file in FreedesktopFiles.Collect(
            bundle, packageName, "/" + installRoot, mainExecutable, binLink,
            new FreedesktopFiles.Options
            {
                DesktopFile = settings.DesktopFile,
                MetainfoFile = settings.MetainfoFile,
                Categories = settings.Categories is { Count: > 0 } categories ? string.Join(";", categories) : null,
                Format = "deb"
            }))
        {
            if (file.SourcePath is { } sourcePath)
            {
                AddFile(file.ArchivePath, sourcePath, file.Mode);
            }
            else
            {
                AddGeneratedFile(file.ArchivePath, file.Content!, file.Mode);
            }
        }

        var docRoot = "usr/share/doc/" + packageName;
        // Debian policy wants the packaging changelog at changelog.Debian.gz;
        // emit a deterministic stub (fixed date matching TarWriter.EntryMtime).
        var debianChangelog = packageName + " (" + version + ") unstable; urgency=low\n\n" +
            "  * Packaged with DotNet.Bundler.\n\n" +
            " -- " + maintainer + "  Tue, 01 Jan 1980 00:00:00 +0000\n";
        AddGeneratedFile(
            docRoot + "/changelog.Debian.gz",
            Gzip(new UTF8Encoding(false).GetBytes(debianChangelog)),
            420 /* 0644 */);
        if (settings.ChangelogFile is { Length: > 0 } changelogSource)
        {
            AddGeneratedFile(
                docRoot + "/changelog.gz",
                Gzip(File.ReadAllBytes(FreedesktopFiles.RequireExisting(changelogSource, "ChangelogFile"))),
                420 /* 0644 */);
        }
        if (bundle.LicenseFile is { Length: > 0 } license)
        {
            AddFile(docRoot + "/copyright", FreedesktopFiles.RequireExisting(license, "LicenseFile"), 420 /* 0644 */);
        }

        foreach (var file in settings.Files ?? [])
        {
            var destination = FreedesktopFiles.NormalizeAbsoluteDestination(
                file.Destination, "deb").TrimStart('/');
            AddFile(destination, FreedesktopFiles.RequireExisting(file.Source, "DebFile"), 420 /* 0644 */);
        }

        if (settings.SystemdServiceFile is { Length: > 0 } unitSource)
        {
            AddFile(
                "usr/lib/systemd/system/" + packageName + ".service",
                FreedesktopFiles.RequireExisting(unitSource, "SystemdServiceFile"), 420 /* 0644 */);
        }

        return entries;
    }

    private static List<TarEntry> ControlEntries(
        BundleConfiguration bundle,
        List<PayloadEntry> payload,
        string packageName,
        string version,
        string architecture,
        string maintainer,
        DebBundleConfiguration settings)
    {
        var control = new StringBuilder();
        control.Append("Package: ").Append(packageName).Append('\n');
        control.Append("Version: ").Append(version).Append('\n');
        control.Append("Architecture: ").Append(architecture).Append('\n');
        control.Append("Maintainer: ").Append(maintainer).Append('\n');
        control.Append("Installed-Size: ").Append(InstalledSize(payload)).Append('\n');
        var priority = (settings.Priority ?? "optional").Trim();
        if (priority is not ("required" or "important" or "standard" or "optional" or "extra"))
        {
            throw new ArgumentException(
                $"'{priority}' is not a valid Debian priority (required|important|standard|optional|extra).");
        }
        control.Append("Priority: ").Append(priority).Append('\n');
        if (settings.Section is { Length: > 0 } section)
        {
            var trimmedSection = section.Trim();
            if (!SectionPattern.IsMatch(trimmedSection))
            {
                throw new ArgumentException(
                    $"'{trimmedSection}' is not a valid Debian archive section (lowercase letters, digits, '+', '-', '.'; optional '/' subsections).");
            }
            control.Append("Section: ").Append(trimmedSection).Append('\n');
        }
        AppendRelation(control, "Depends", settings.Depends);
        AppendRelation(control, "Recommends", settings.Recommends);
        AppendRelation(control, "Provides", settings.Provides);
        AppendRelation(control, "Conflicts", settings.Conflicts);
        AppendRelation(control, "Replaces", settings.Replaces);
        if (!string.IsNullOrWhiteSpace(bundle.Homepage))
        {
            if (bundle.Homepage!.IndexOfAny(['\r', '\n']) >= 0)
            {
                throw new ArgumentException("The homepage must be a single line.");
            }
            control.Append("Homepage: ").Append(bundle.Homepage).Append('\n');
        }
        var description = (bundle.Description ?? "").Replace("\r\n", "\n").Replace('\r', '\n');
        var lines = description.Split('\n');
        var shortDescription = lines.FirstOrDefault(line => line.Trim().Length > 0)?.Trim()
            ?? bundle.ProductName;
        control.Append("Description: ").Append(shortDescription).Append('\n');
        var extended = string.Join("\n", lines.SkipWhile(line => line.Trim().Length == 0).Skip(1)
            .Select(line => line.Trim().Length == 0 ? " ." : " " + line.TrimEnd()));
        if (extended.Length == 0)
        {
            extended = " Packaged with DotNet.Bundler.";
        }
        control.Append(extended).Append('\n');

        var md5sums = new StringBuilder();
        foreach (var entry in payload.Where(e => e.Kind == TarEntryKind.File))
        {
            var hash = entry.Content is { } inline
                ? Md5Hex(inline)
                : Md5HexFile(entry.SourcePath!);
            md5sums.Append(hash).Append("  ").Append(entry.ArchivePath).Append('\n');
        }

        var entries = new List<TarEntry>
        {
            new() { Name = "./control", Kind = TarEntryKind.File, Mode = 420 /* 0644 */,
                Content = new UTF8Encoding(false).GetBytes(control.ToString()) },
            new() { Name = "./md5sums", Kind = TarEntryKind.File, Mode = 420 /* 0644 */,
                Content = new UTF8Encoding(false).GetBytes(md5sums.ToString()) }
        };

        var conffiles = ConffilePaths(payload, settings);
        if (conffiles.Length > 0)
        {
            entries.Add(new TarEntry
            {
                Name = "./conffiles", Kind = TarEntryKind.File, Mode = 420 /* 0644 */,
                Content = new UTF8Encoding(false).GetBytes(string.Join("\n", conffiles) + "\n")
            });
        }

        // Maintainer scripts land in the control archive with mode 0755. A
        // systemd unit auto-appends a daemon-reload epilogue to postinst.
        var daemonReload = settings.SystemdServiceFile is { Length: > 0 };
        AddScript(entries, "preinst", settings.PreInstallFile);
        var postinst = settings.PostInstallFile is { Length: > 0 }
            ? ReadScript(settings.PostInstallFile, "PostInstallFile")
            : null;
        if (daemonReload)
        {
            var body = postinst is null
                ? "#!/bin/sh\nset -e\n"
                : postinst + "\n";
            body += "\n# Bundler: systemd unit installed; reload unit definitions.\n" +
                "systemctl daemon-reload || true\n";
            postinst = body;
        }
        if (postinst is not null)
        {
            entries.Add(new TarEntry
            {
                Name = "./postinst", Kind = TarEntryKind.File, Mode = 493 /* 0755 */,
                Content = new UTF8Encoding(false).GetBytes(postinst)
            });
        }
        AddScript(entries, "prerm", settings.PreUninstallFile);
        AddScript(entries, "postrm", settings.PostUninstallFile);

        return entries;
    }

    private static string[] ConffilePaths(List<PayloadEntry> payload, DebBundleConfiguration settings)
    {
        var payloadFiles = new HashSet<string>(
            payload.Where(e => e.Kind == TarEntryKind.File).Select(e => e.ArchivePath),
            StringComparer.Ordinal);
        var conffiles = new List<string>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        void Add(string destination, string knob)
        {
            var path = destination.Trim().Replace('\\', '/');
            if (!path.StartsWith("/", StringComparison.Ordinal) ||
                path.Split('/').Skip(1).Any(segment => segment is "" or "." or ".."))
            {
                throw new ArgumentException(
                    $"A {knob} entry must be an absolute package path: '{destination}'.");
            }
            var archivePath = path.TrimStart('/');
            if (!payloadFiles.Contains(archivePath))
            {
                throw new ArgumentException(
                    $"The {knob} entry '{path}' has no file in the payload.");
            }
            if (seen.Add(path))
            {
                conffiles.Add(path);
            }
        }
        foreach (var file in settings.Files ?? [])
        {
            var destination = file.Destination.Trim().Replace('\\', '/');
            if (destination.StartsWith("/etc/", StringComparison.Ordinal))
            {
                Add(destination, "DebFile(/etc)");
            }
        }
        foreach (var path in settings.ConfigLocations ?? [])
        {
            Add(path, "Conffiles");
        }
        return conffiles.ToArray();
    }

    private static void AddScript(List<TarEntry> entries, string name, string? file)
    {
        if (file is not { Length: > 0 })
        {
            return;
        }
        entries.Add(new TarEntry
        {
            Name = "./" + name, Kind = TarEntryKind.File, Mode = 493 /* 0755 */,
            Content = new UTF8Encoding(false).GetBytes(ReadScript(file, name + "File"))
        });
    }

    private static string ReadScript(string path, string knob)
    {
        var full = FreedesktopFiles.RequireExisting(path, knob);
        var text = File.ReadAllText(full);
        if (!text.StartsWith("#!", StringComparison.Ordinal))
        {
            throw new ArgumentException(
                $"The .deb maintainer script '{knob}' must start with a shebang: {full}");
        }
        if (text.IndexOf('\r') >= 0)
        {
            throw new ArgumentException(
                $"The .deb maintainer script '{knob}' must use LF line endings: {full}");
        }
        return text;
    }

    private static readonly System.Text.RegularExpressions.Regex SectionPattern = new(
        "^[a-z0-9][a-z0-9+.-]*(/[a-z0-9][a-z0-9+.-]*)*$",
        System.Text.RegularExpressions.RegexOptions.Compiled);

    private static void AppendRelation(StringBuilder control, string field, IReadOnlyList<string>? clauses)
    {
        if (clauses is not { Count: > 0 })
        {
            return;
        }
        var trimmed = clauses.Select(clause => clause.Trim()).ToArray();
        if (trimmed.Any(clause => clause.Length == 0 || clause.IndexOfAny(new[] { '\r', '\n' }) >= 0))
        {
            throw new ArgumentException(
                $"The .deb {field} entries must be non-empty single lines.");
        }
        control.Append(field).Append(": ").Append(string.Join(", ", trimmed)).Append('\n');
    }

    private static int InstalledSize(List<PayloadEntry> payload)
    {
        // KiB occupied: files rounded up to a 1 KiB block each, plus one block per
        // directory or link (dpkg's du-style accounting).
        long total = 0;
        foreach (var entry in payload)
        {
            total += entry.Kind == TarEntryKind.File
                ? (entry.Size + 1023) / 1024
                : 1;
        }
        return (int)Math.Max(total, 1);
    }

    // data tar 直写 gzip→文件：TarWriter 的 OpenContent 已惰性流源文件，
    // 这一层再把 tar/gzip 字节驻内存才是唯一的整量缓冲点。
    private static void GzipTarToFile(IEnumerable<PayloadEntry> entries, string path)
    {
        using var file = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None);
        using (var gzip = new GZipStream(file, CompressionLevel.Optimal, leaveOpen: true))
        {
            TarWriter.Write(gzip, entries
                .OrderBy(entry => entry.ArchivePath, StringComparer.Ordinal)
                .Select(entry => new TarEntry
                {
                    Name = "./" + entry.ArchivePath,
                    Kind = entry.Kind,
                    Mode = entry.Mode,
                    Content = entry.Kind == TarEntryKind.File
                        ? entry.Content ?? []
                        : [],
                    OpenContent = entry.Kind == TarEntryKind.File && entry.Content is null
                        ? () => new FileStream(entry.SourcePath!, FileMode.Open, FileAccess.Read, FileShare.Read)
                        : null,
                    LinkTarget = entry.LinkTarget
                }));
        }
    }

    private static void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch
        {
            // 临时件清扫失败不遮主流程。
        }
    }

    private static byte[] TarBytes(IEnumerable<TarEntry> entries)
    {
        using var buffer = new MemoryStream();
        TarWriter.Write(buffer, entries);
        return buffer.ToArray();
    }

    private static byte[] Gzip(byte[] content)
    {
        using var buffer = new MemoryStream();
        using (var gzip = new GZipStream(buffer, CompressionLevel.Optimal, leaveOpen: true))
        {
            gzip.Write(content, 0, content.Length);
        }
        return buffer.ToArray();
    }

    private static string MapArchitecture(CpuArchitecture architecture) => architecture switch
    {
        CpuArchitecture.X64 => "amd64",
        CpuArchitecture.Arm64 => "arm64",
        CpuArchitecture.X86 => "i386",
        _ => throw new NotSupportedException(
            $"No Debian architecture mapping for {architecture}; set Architecture explicitly.")
    };

    private static void ValidateArchitecture(string architecture)
    {
        if (!architecture.All(c => char.IsLower(c) || char.IsDigit(c) || c == '-') ||
            architecture.Length == 0)
        {
            throw new ArgumentException(
                $"'{architecture}' is not a valid Debian architecture (lowercase letters, digits, '-').");
        }
    }

    // Returns the tar-relative path (no leading '/'), e.g. "usr/lib/pkg".
    private static string NormalizeInstallRoot(string? installRoot, string packageName)
    {
        var root = string.IsNullOrWhiteSpace(installRoot)
            ? "/usr/lib/" + packageName
            : installRoot!.Trim();
        if (!root.StartsWith("/", StringComparison.Ordinal))
        {
            throw new ArgumentException(
                $"The .deb install root must be an absolute path: '{root}'.");
        }
        var normalized = root.Trim('/');
        if (normalized.Length == 0 ||
            normalized.Split('/').Any(segment => segment is "" or "." or ".."))
        {
            throw new ArgumentException(
                $"The .deb install root contains an invalid segment: '{root}'.");
        }
        return normalized;
    }

    private static void ValidateBinLinkName(string name)
    {
        if (name.IndexOfAny(new[] { '/', '\\' }) >= 0 ||
            name is "." or ".." ||
            name.Trim().Length != name.Length || name.Length == 0)
        {
            throw new ArgumentException(
                $"'{name}' is not a valid /usr/bin link name (a bare file name).");
        }
    }

    private static string RelativePath(string baseDirectory, string path)
    {
        var prefix = Path.GetFullPath(baseDirectory)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) +
            Path.DirectorySeparatorChar;
        var full = Path.GetFullPath(path);
        if (!full.StartsWith(prefix, StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"A payload path escapes its base directory: '{path}'.");
        }
        return full.Substring(prefix.Length);
    }

    private static string ToPosixPath(string path) =>
        path.Replace(Path.DirectorySeparatorChar, '/').Replace(Path.AltDirectorySeparatorChar, '/');

    private static string Md5Hex(byte[] content)
    {
        using var md5 = MD5.Create();
        return Hex(md5.ComputeHash(content));
    }

    private static string Md5HexFile(string path)
    {
        using var md5 = MD5.Create();
        using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
        return Hex(md5.ComputeHash(stream));
    }

    private static string Sha256HexFile(string path)
    {
        using var sha256 = SHA256.Create();
        using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
        return Hex(sha256.ComputeHash(stream));
    }

    internal static string Sha256Hex(byte[] content)
    {
        using var sha256 = SHA256.Create();
        return Hex(sha256.ComputeHash(content));
    }

    private static string Hex(byte[] hash)
    {
        var builder = new StringBuilder(hash.Length * 2);
        foreach (var b in hash)
        {
            builder.Append(b.ToString("x2", System.Globalization.CultureInfo.InvariantCulture));
        }
        return builder.ToString();
    }
}
