<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\TestPlatform.cs" />
    <ProjectReference Include="..\..\src\Bundler.Core\Bundler.Core.csproj" />
    <ProjectReference Include="..\..\src\Bundler.AlpineApk\Bundler.AlpineApk.csproj" />
    <ProjectReference Include="..\..\src\Bundler.AppImage\Bundler.AppImage.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Archive\Bundler.Archive.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Deb\Bundler.Deb.csproj" />
    <ProjectReference Include="..\..\src\Bundler.MacApp\Bundler.MacApp.csproj" />
    <ProjectReference Include="..\..\src\Bundler.MacDmg\Bundler.MacDmg.csproj" />
    <ProjectReference Include="..\..\src\Bundler.MacPkg\Bundler.MacPkg.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Nsis\Bundler.Nsis.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Rpm\Bundler.Rpm.csproj" />
    <ProjectReference Include="..\..\src\Bundler.Wix\Bundler.Wix.csproj" />
  </ItemGroup>
</Project>
