using System.Text;

namespace DotNet.Bundler.Core;

/// <summary>
/// Shared freedesktop.org file staging for the Linux backends (.deb/.rpm):
/// the generated or caller-supplied .desktop entry under
/// <c>usr/share/applications/</c>, hicolor PNG icons with IHDR size probing
/// (the <c>@2x</c> file-name suffix maps to the <c>@2</c> scale slot) and the
/// optional AppStream metainfo file under <c>usr/share/metainfo/</c>.
/// Produced paths are relative ("usr/share/..."); each writer maps them onto
/// its own archive convention.
/// </summary>
internal static class FreedesktopFiles
{
    internal sealed class Entry
    {
        internal string ArchivePath = "";   // relative path, no leading '/'
        internal int Mode = 420 /* 0644 */;
        internal string? SourcePath;        // host file when not generated
        internal byte[]? Content;           // generated bytes otherwise

        internal byte[] ReadBytes() => Content ?? File.ReadAllBytes(SourcePath!);
    }

    internal sealed class Options
    {
        internal string? DesktopFile;    // verbatim .desktop replacement
        internal string? MetainfoFile;   // AppStream metainfo XML
        internal string? Categories;     // freedesktop semicolon categories
        internal string Format = "";     // "deb"/"rpm" — error context only
        internal bool AlwaysEmitIcon;    // appimage: Icon= is mandatory (icon fallback guaranteed)
    }

    /// <summary>
    /// Stages the .desktop entry (generated from <paramref name="bundle"/> unless
    /// <see cref="Options.DesktopFile"/> supplies one verbatim), every icon under
    /// hicolor and the optional metainfo file.
    /// </summary>
    internal static List<Entry> Collect(
        BundleConfiguration bundle,
        string packageName,
        string installRoot,
        string mainExecutable,
        string binLink,
        Options options)
    {
        var entries = new List<Entry>
        {
            new Entry
            {
                ArchivePath = "usr/share/applications/" + packageName + ".desktop",
                Content = options.DesktopFile is { Length: > 0 } desktopSource
                    ? File.ReadAllBytes(RequireExisting(desktopSource, "DesktopFile"))
                    : DesktopFileContent(
                        bundle, packageName, installRoot, mainExecutable, binLink,
                        options.Categories, options.Format, options.AlwaysEmitIcon)
            }
        };

        foreach (var icon in bundle.Icons)
        {
            var iconSource = RequireExisting(icon, "Icons");
            var iconBytes = File.ReadAllBytes(iconSource);
            entries.Add(new Entry
            {
                ArchivePath = HicolorIconDirectory(icon, iconBytes) + "/" + packageName + ".png",
                Content = iconBytes
            });
        }

        if (options.MetainfoFile is { Length: > 0 } metainfoSource)
        {
            entries.Add(new Entry
            {
                ArchivePath = "usr/share/metainfo/" + packageName + ".metainfo.xml",
                SourcePath = RequireExisting(metainfoSource, "MetainfoFile")
            });
        }

        return entries;
    }

    /// <summary>
    /// Resolves a caller-supplied file path and fails when it is missing.
    /// <paramref name="knob"/> names the setting for the error message.
    /// </summary>
    internal static string RequireExisting(string path, string knob)
    {
        var full = Path.GetFullPath(path);
        if (!File.Exists(full))
        {
            throw new FileNotFoundException(
                $"The {knob} file does not exist: {full}", full);
        }
        return full;
    }

    /// <summary>
    /// Normalizes a caller-supplied package destination to a canonical absolute
    /// path (<c>/etc/app/x.conf</c>): slashes unified, surrounding slashes
    /// removed, every segment validated. Rejects empty, relative, trailing-slash
    /// or dot-segment destinations.
    /// </summary>
    internal static string NormalizeAbsoluteDestination(string destination, string format)
    {
        var normalized = destination.Replace('\\', '/').Trim('/');
        if (destination.Trim().Length == 0 ||
            !destination.TrimStart().StartsWith("/", StringComparison.Ordinal) ||
            normalized.Length == 0 ||
            normalized.Split('/').Any(segment =>
                segment is "" or "." or ".." || segment.All(char.IsWhiteSpace)) ||
            normalized.EndsWith("/", StringComparison.Ordinal) ||
            destination.Replace('\\', '/').EndsWith("/", StringComparison.Ordinal))
        {
            throw new ArgumentException(
                $"The .{format} file destination must be an absolute path with a file name: '{destination}'.");
        }
        return "/" + normalized;
    }

    internal static byte[] DesktopFileContent(
        BundleConfiguration bundle,
        string packageName,
        string installRoot,
        string mainExecutable,
        string binLink,
        string? categories,
        string format,
        bool alwaysEmitIcon = false)
    {
        static string SanitizeDesktopValue(string? value, string field)
        {
            var trimmed = (value ?? "").Trim();
            if (trimmed.IndexOfAny(new[] { '\r', '\n', '\0' }) >= 0)
            {
                throw new ArgumentException(
                    $"The .desktop {field} must be a single line.");
            }
            return trimmed;
        }

        // Desktop Entry 规范：引号内 '"' '`' '$' '\' 要反斜杠转义；保留字符 '%' 要成对。
        static string QuoteExecArgument(string argument)
    {
        var escaped = argument.Replace("%", "%%");
        if (escaped.Length > 0 &&
            !escaped.Any(character => char.IsWhiteSpace(character) ||
                                      character is '"' or '\'' or '\\' or ';' or '&' or '|' or
                                      '<' or '>' or '(' or ')' or '$' or '`' or '~' or '*' or '?' or '#'))
        {
            return escaped;
        }
        return "\"" + escaped
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("`", "\\`")
            .Replace("$", "\\$") + "\"";
        }

        var builder = new StringBuilder();
        builder.Append("[Desktop Entry]\n");
        builder.Append("Type=Application\n");
        builder.Append("Name=").Append(SanitizeDesktopValue(bundle.ProductName, "Name")).Append('\n');
        var comment = SanitizeDesktopValue(
            (bundle.Description ?? "").Split('\n').FirstOrDefault(line => line.Trim().Length > 0),
            "Comment");
        if (comment.Length > 0)
        {
            builder.Append("Comment=").Append(comment).Append('\n');
        }
        // Exec prefers the usr/bin link; without it the absolute install-root path is used.
        // 桌面规范：Exec 参数要引号/百分号转义，否则含空格或 '%' 的路径产出非法行。
        var exec = QuoteExecArgument(binLink.Length > 0 ? binLink : installRoot + "/" + mainExecutable);
        var hasUrls = bundle.UrlProtocols.Any(p => p.Schemes.Count > 0);
        var hasFiles = bundle.FileAssociations.Any(a => a.Extensions.Count > 0);
        builder.Append("Exec=").Append(exec)
            .Append(hasUrls ? " %u" : hasFiles ? " %f" : "").Append('\n');
        if (bundle.Icons.Count > 0 || alwaysEmitIcon)
        {
            builder.Append("Icon=").Append(packageName).Append('\n');
        }
        builder.Append("Terminal=false\n");
        if (categories is { Length: > 0 })
        {
            var list = categories.Split(';')
                .Select(c => c.Trim())
                .Where(c => c.Length > 0)
                .ToArray();
            if (list.Length == 0 || list.Any(c => !c.All(ch => char.IsLetterOrDigit(ch) || ch is '-' or '_')))
            {
                throw new ArgumentException(
                    $"Bundler{format}Categories must be a semicolon list of freedesktop categories, got '{categories}'.");
            }
            builder.Append("Categories=").Append(string.Join(";", list)).Append(";\n");
        }
        var mimeTypes = bundle.FileAssociations
            .Select(a => a.MimeType)
            .Where(m => !string.IsNullOrWhiteSpace(m))
            .Select(m => m!.Trim())
            .Concat(bundle.UrlProtocols
                .SelectMany(p => p.Schemes)
                .Where(scheme => !string.IsNullOrWhiteSpace(scheme))
                .Select(scheme => "x-scheme-handler/" + scheme.Trim()))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (mimeTypes.Any(m => m.IndexOf('/') <= 0 || m.IndexOfAny(new[] { ' ', '\t', ';' }) >= 0))
        {
            throw new ArgumentException(
                $"Invalid MimeType entry for the .desktop file: '{string.Join(";", mimeTypes)}'.");
        }
        if (mimeTypes.Length > 0)
        {
            builder.Append("MimeType=").Append(string.Join(";", mimeTypes)).Append(";\n");
        }
        return new UTF8Encoding(false).GetBytes(builder.ToString());
    }

    private static string HicolorIconDirectory(string iconPath, byte[] content)
    {
        var (width, height) = PngSize(content);
        var stem = Path.GetFileNameWithoutExtension(iconPath);
        var scale = 1;
        if (stem.EndsWith("@2x", StringComparison.OrdinalIgnoreCase))
        {
            scale = 2;
        }
        if (width % scale != 0 || height % scale != 0)
        {
            throw new ArgumentException(
                $"The icon '{iconPath}' pixel size {width}x{height} is not divisible by its {scale}x density.");
        }
        var logicalWidth = width / scale;
        var logicalHeight = height / scale;
        return "usr/share/icons/hicolor/" + logicalWidth + "x" + logicalHeight +
            (scale == 1 ? "" : "@2") + "/apps";
    }

    private static (int Width, int Height) PngSize(byte[] content)
    {
        var signature = new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A };
        if (content.Length < 24 ||
            !content.Take(8).SequenceEqual(signature) ||
            content[12] != 'I' || content[13] != 'H' || content[14] != 'D' || content[15] != 'R')
        {
            throw new ArgumentException(
                "Only PNG icons are supported: the file is not a PNG or its IHDR is missing.");
        }
        var width = (content[16] << 24) | (content[17] << 16) | (content[18] << 8) | content[19];
        var height = (content[20] << 24) | (content[21] << 16) | (content[22] << 8) | content[23];
        if (width <= 0 || height <= 0)
        {
            throw new ArgumentException("The PNG icon reports a non-positive dimension.");
        }
        return (width, height);
    }
}
