<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DotNet.Bundler.MSBuild</AssemblyName>
    <RootNamespace>DotNet.Bundler.MSBuild</RootNamespace>
    <GenerateDependencyFile>true</GenerateDependencyFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core"
                      Version="17.8.43"
                      PrivateAssets="all"
                      ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
