<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <BundlerPackageVersion Condition="'$(BundlerPackageVersion)' == ''">0.1.0-alpha.24</BundlerPackageVersion>
    <RestoreSources>$(BundlerPackageSource);https://api.nuget.org/v3/index.json</RestoreSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNet.Bundler.Nsis" Version="$(BundlerPackageVersion)" />
  </ItemGroup>
</Project>
